#!/usr/bin/env bash
#display from 1 to 100 with telling if the numbers are multiple of 3 or 5 or both
i=1
while [ $i -lt 101 ]
do
	if [ $((i%15)) = 0 ]

	then 
		echo "FizzBuzz"
	elif [ $((i%3)) = 0 ]
	then 
		echo "Fizz"
	elif [ $((i%5)) = 0 ] 
	then
		echo "Buzz"
	else 
	echo $i
fi
((i++))
done
