#!/usr/bin/env bash     
#this file is going to add 4 blocks in between lines 
i=0
while [ $i -le 19 ]
do
	((i++))
	case $i in 
	4)
		echo "$i"
		echo  "bad luck from China"
		;;
    	9)
    		echo "$i"
    		echo  "bad luck from Japan"
    		;;
    	17)
    		echo "$i"
    		echo "bad luck from Italy"
    		;;
    	*)
        	echo $i
        	;;
	esac
done
