#!/usr/bin/env bash
#information
touch /var/run/myscript.pid > "$BASHPID"
while true 
do 
	echo "To infinity and beyond"
	trap " echo I hate the kill command ; rm /var/run/myscript.pid ; exit" SIGTERM
	trap " echo Y U no love me?! ; rm /var/run/myscript.pid ; exit " SIGINT
	
done

